# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: dd3e3b4eef9968e308dbc6ea5a67cb053c2dfa497056d3c5e7ca1e2c75021e577a53f48d1059335d8787eb5e79b30a23f4a8f5b6b2c9441985ba279359989dd2

test:
  domain_name: example.com 
  secret_key_base: 08c8796d6122ce74a0ade47b3380440899c57e327701e0ecabb3d49291065883b7f8444ba57f9687cd452a3fe39faa70e7da6a828db766f5829209b54a16de83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
